Expose resampling option
frequenz-floss/frequenz-client-reporting-python pull request #52
Opened 2024-05-03 13:44 UTC by flora-hofmann-frequenz

Addressing issue #22 by exposing the resampling option as an optional input.

2024-05-03 16:37 UTC, cwasicki reviewed
Just minor comments on default, otherwise LGTM

2024-05-03 16:37 UTC, cwasicki commented on examples/client.py
> +    parser.add_argument("--resolution", type=int, help="Resolution", default=1)
That can also be None, i.e. no resampling. I would also make this the default.

2024-05-03 16:37 UTC, cwasicki commented on src/frequenz/client/reporting/_client.py
> +        resolution: int = 1,
Also here it can be `None` too, and I suggest to make this the default.

2024-05-03 16:37 UTC, cwasicki commented on src/frequenz/client/reporting/_client.py
> +        resolution: int = 1,
See above

2024-05-03 16:37 UTC, cwasicki commented on src/frequenz/client/reporting/_client.py
> +        resolution: int = 1,
I would remove the default here completely. (And for page size too IMO)

2024-05-03 16:44 UTC, cwasicki commented on src/frequenz/client/reporting/_client.py
> +        )
You could move this into [this line](https://github.com/frequenz-floss/frequenz-client-reporting-python/pull/52/files#diff-bc44ef8bfdafafc5ae638f3475097e7459739c5eda848f6954aa620b48f2e50aR255) to avoid the CI failure.

2024-05-06 10:05 UTC, cwasicki commented on src/frequenz/client/reporting/_client.py
> +        resolution: Optional[int] = None,
You don't need the `Optional`, this can be `int | None`

2024-05-06 18:49 UTC, cwasicki requested changes

2024-05-06 18:49 UTC, cwasicki commented on src/frequenz/client/reporting/_client.py
> +from typing import Any, AsyncIterator, Awaitable, Iterator, Optional, Type, cast
The `Optional` can go.

2024-05-06 18:49 UTC, cwasicki commented on src/frequenz/client/reporting/_client.py
> +        resolution: Optional[int],
One more `Optional` left.

2024-05-07 06:29 UTC, flora-hofmann-frequenz commented on src/frequenz/client/reporting/_client.py
> +        resolution: Optional[int],
When I took it out yesterday, I got an error here: `return self._data_pb.pagination_info.next_page_token`

Now I tried it again, and the error's not there anymore? Sorry about that!
I have taken it out.

2024-05-08 10:35 UTC, cwasicki approved these changes

2024-05-08 10:49 UTC, merged